---
# Setup LAMP Stack
- name: Install LAMP stack
  hosts: test
  tasks:
    - name: install lamp stack
      become: yes
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - apache2
        - mysql-server
        - php
        - php-mysql
    - name: start services
      service: name={{ item }} state=started enabled=yes
      become: yes
      with_items:
        - apache2
        - mysql
    - name: deploy index.html
      become: yes
      copy:
        src: /Users/leoclarke/Documents/github/ansible-server-setup/tmp/index.html
        dest: /var/www/html/index.html
